Fix NPE in TestRunSession#toString
eclipse-platform/eclipse.platform pull request #1213
Opened 2024-02-27 10:00 UTC by laeubi

currently if one calls TestRunSession#toString (e.g. in a debugger) a NPE can occur if the session is not yet started and the fStartTime is null.

This checks for this case and adjust the message accordingly and also replace the volatile boolean with an AtomicBoolean.

2024-03-08 12:33 UTC, jukzi requested changes
There is no need for AtomicReference
"This class is immutable and thread-safe."
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html

the rest looks good.

2024-03-12 05:29 UTC, laeubi commented
> There is no need for AtomicReference "This class is immutable and thread-safe." https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html
> 
> the rest looks good.

The class is threadsafe, but not the access to its instance.

2024-03-12 07:13 UTC, jukzi commented
> The class is threadsafe, but not the access to its instance.

That was done by the volatile keyword.

2024-05-11 16:42 UTC, laeubi commented
I adjusted the commit message now.

2025-02-05 13:07 UTC, closed without merging