[Cheat Sheets] Add Icon in the Help Menu
eclipse-platform/eclipse.platform pull request #1292
Opened 2024-04-08 11:04 UTC by N1k145

fixes #1291

Adds the existing Cheat Sheet Icon to the "Cheat Sheets.." Help Menu Entry

2024-04-08 11:14 UTC, merks commented
@BeckerWdf @N1k145 

It's not so common to reference images from another bundle:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/11600b27-7ede-4530-84cc-151105e56010)

Even some of the above aren't actually referencing another bundle's image.

I wonder too about the use of a "view" image on the menu.  Might that be problematic in the future?

I realize it's quite heavy weight to introduce an icon to this bundle, and to the images repository...

2024-04-08 11:55 UTC, N1k145 commented
@merks Thank you for your Insight.

For me, it was not uncommon to do it like this, especially as there is already a dependency between these bundles. 

My Intention was to not duplicate the image, as they are already present in the Cheat Sheet bundle.

I was also wondering why this is implemented in the platform bundle and not the Cheat Sheet bundle, but the discussion here gave some insight https://bugs.eclipse.org/bugs/show_bug.cgi?id=120087

If the "view" image will be an issue, IDK. I chose that image because it's the main image which is associated with Cheat Sheets, as it is the view icon.

2024-04-08 13:31 UTC, N1k145 commented
@BeckerWdf I duplicated the icon and put it to the other images in the plugin

2024-04-08 13:36 UTC, merks commented
@BeckerWdf 

From experience I know that such images originate from here:

https://github.com/eclipse-platform/eclipse.platform.images/blob/master/org.eclipse.images/eclipse-svg/org.eclipse.ui.cheatsheets/icons/view16/cheatsheet_view.svg

I also know there is a pretty "strict" folder naming convention involved so that one knows the role the image plays.

https://github.com/eclipse-platform/eclipse.platform.images/tree/master/org.eclipse.images/eclipse-svg/org.eclipse.ui.cheatsheets/icons

Is that convention documented somewhere?  Also, will images need to be copied in the https://github.com/eclipse-platform/eclipse.platform.images repository to the appropriately named folder location?

@N1k145 

Sorry, I'm not trying to create more work for you.  😞   I'm just trying to avoid creating work and surprises for someone else in the future if there are efforts to provide newer images in the future.

2024-04-08 14:24 UTC, merks commented
I'm going to leave it to @BeckerWdf  to review and approve.  I'm just trying to be helpful, but traveling for most of the week and would only hold things up.

2024-04-08 14:27 UTC, BeckerWdf requested changes

2024-04-09 04:56 UTC, N1k145 commented on platform/org.eclipse.platform/images/cheatsheet_view.png
Done, should I leave them in the images folder or move them to a new icons/obj16 folder?

2024-04-09 05:28 UTC, merks commented on platform/org.eclipse.platform/images/cheatsheet_view.png
There aren't many images folders:
```
$ls */images
org.eclipse.e4.ui.workbench.swt/images:
dragHandle-rotated.svg  dragHandle.svg

org.eclipse.jdt/images:
topiclabel/

org.eclipse.pde/images:
topiclabel/

org.eclipse.platform/images:
topiclabel/
```

I would find one of the other icons shown on the menus, and use the same folder name convention.  E.g., for the Help Contents it's like this:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/41e1e3ffcccd9c4253f76d68bf5324a8092eac6b/bundles/org.eclipse.ui/plugin.xml#L1516-L1519

I suppose the $nls$ is for translations to provide different icons...

2024-04-09 05:29 UTC, BeckerWdf commented on platform/org.eclipse.platform/images/cheatsheet_view.png
mh. pls create a new folder according to https://eclipse-platform.github.io/ui-best-practices/#folder_structure 
(i think "/icons/tool" would be the correct location) and also keep the same structure in the images repo.

2024-04-09 05:31 UTC, BeckerWdf commented on platform/org.eclipse.platform/images/cheatsheet_view.png
> I would find one of the other icons shown on the menus, and use the same folder name convention. E.g., for the Help Contents it's like this:
> 
> https://github.com/eclipse-platform/eclipse.platform.ui/blob/41e1e3ffcccd9c4253f76d68bf5324a8092eac6b/bundles/org.eclipse.ui/plugin.xml#L1516-L1519

that's also ok for me.

>I suppose the 
 is for translations to provide different icons...
 
 yes

2024-04-09 05:41 UTC, N1k145 commented on platform/org.eclipse.platform/images/cheatsheet_view.png
@merks @BeckerWdf 
I moved the icons now to /icons/etool16/ and added the translation tag

2024-04-09 05:58 UTC, BeckerWdf approved these changes

2024-04-09 05:58 UTC, BeckerWdf commented
LGTM. I'll merge once CI is happy with this change.

2024-04-09 07:32 UTC, BeckerWdf commented
Test org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest is failing. Can this be related to this change? I don't think so.

2024-04-09 07:34 UTC, BeckerWdf commented
is it necessary to add the new "icons" folder to the build.properties file in the "bin.includes" key?

2024-04-09 07:38 UTC, iloveeclipse commented
> is it necessary to add the new "icons" folder to the build.properties file in the "bin.includes" key?

Sure. What's nit included will be not in the bundle.

2024-04-09 08:08 UTC, N1k145 commented
@BeckerWdf @iloveeclipse thanks, no idea how I missed that...

2024-04-09 08:19 UTC, merks commented
At development time all the content visible in the root folder are visible in the self-hosted launch bundle so it is easy to overlook.

2024-04-09 10:48 UTC, BeckerWdf commented
> At development time all the content visible in the root folder are visible in the self-hosted launch bundle so it is easy to overlook.

I *always* oversee this. ;-)

2024-04-09 10:48 UTC, BeckerWdf approved these changes

2024-04-09 10:50 UTC, BeckerWdf commented
failing tests

```
[org.eclipse.core.tests.internal.builders.ParallelBuildChainTest.testIndividualProjectBuilds_WithManyProjects_ProjectRelaxedRule](https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1292/6/testReport/junit/org.eclipse.core.tests.internal.builders/ParallelBuildChainTest/testIndividualProjectBuilds_WithManyProjects_ProjectRelaxedRule/)
[org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks](https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1292/6/testReport/junit/org.eclipse.ua.tests.doc.internal.linkchecker/LinkTest/testAllLinks/)

```
are unrelated

2024-04-09 10:50 UTC, merged

2024-04-09 10:50 UTC, BeckerWdf commented
@N1k145 thanks for your contribution