Improve DSA and RSA key generation bit size.
eclipse-platform/eclipse.platform pull request #1600
Opened 2024-10-27 01:04 UTC by axmanalad

Generating a DSA or RSA key originally gave a bit size of 1024, which is not the recommended bit size of 2048 nor the stronger bit size of 4096.
This change allows a DSA-3072 key or an RSA-4096 key to be generated.
Note: DSA-4096 is not possible with the current algorithm of the DSA key generator. Therefore, DSA-3072 is implemented instead of DSA-4096.

Original PR from #1596
Fixes #1464

2024-10-28 20:53 UTC, HannesWell requested changes
Thank you for creating this follow-up.

Can you please first make sure that you don't revert changes made before, i.e. your commit `Reverted merge changes` is removed. If you have trouble compiling, you probably have to update your target-platform. You can do that for example by re-running your Oomph setup in your workspace.

After that, please squash all your changes into one commit with a meaningful message, In the commit message body you ideally also reference the issue fixed with this. E.g. using
`Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1464`.
If you squash your change please don't include the change the eclipse-platform-bot has pushed to this branch. This should stay separated.

If you subsequently apply changes from the review, please just amend your commit and force-push to the branch.

2024-11-01 06:31 UTC, axmanalad commented
Thank you for the feedback. I was able to remove the `Reverted merge changes` commit and squashed my changes into one commit.
> After that, please squash all your changes into one commit with a meaningful message, In the commit message body you ideally also reference the issue fixed with this. E.g. using `Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1464`. If you squash your change please don't include the change the eclipse-platform-bot has pushed to this branch. This should stay separated.

As someone who is still learning about Git, this comment was very helpful. Let me know if there are any more changes needed to be made.

2024-11-03 19:31 UTC, HannesWell requested changes
>> After that, please squash all your changes into one commit with a meaningful message, In the commit message body you ideally also reference the issue fixed with this. E.g. using Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1464. If you squash your change please don't include the change the eclipse-platform-bot has pushed to this branch. This should stay separated.
> As someone who is still learning about Git, this comment was very helpful. Let me know if there are any more changes needed to be made.

You are welcome and thanks for the update:)

But with referencing `Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1464` I meant to mention it at the end of the commit message body and not only in the headline. The commit headline should still be a descriptive (half) sentence, just like this PR's name/headline. The following body can then contain more details and the mentioned reference.
The overall commit message could be for example (feel free to further adjust this):
```
[SSH] Increase bit-size of generated RSA and DSA keys

Generate RSA keys with 4096bit and DSA keys with 3072 (the underlying algorithm doesn't support higher values)

Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1464
```

Regarding the implementation I have a two comments below.

2024-11-03 19:31 UTC, HannesWell commented on team/bundles/org.eclipse.jsch.ui/src/org/eclipse/jsch/internal/ui/preference/PreferencePage.java
> +					}
```suggestion
					kpairComment = _type + "-" + keySize; //$NON-NLS-1$
```

2024-11-03 19:31 UTC, HannesWell commented on team/bundles/org.eclipse.jsch.ui/src/org/eclipse/jsch/internal/ui/preference/PreferencePage.java
> +							}
As suggested in https://github.com/eclipse-platform/eclipse.platform/issues/1464#issuecomment-2439600327, I think the key-size for RSA and DSA should be specified in a static final int constant at the top of this class:
```
private static final String SSH2_PREFERENCE_PAGE_CONTEXT="org.eclipse.jsch.ui.ssh2_preference_page_context"; //$NON-NLS-1$
private static final int RSA_KEY_SIZE = 4096;
private static final int DSA_KEY_SIZE = 3072;
```

Then you can create a variable in this method, before `BusyIndicator.showWhile()` that holds the actual keySize used for the specified key type:
```
int keySize = type == KeyPair.RSA ? RSA_KEY_SIZE : DSA_KEY_SIZE;
final JSchException[] _e=new JSchException[1];
BusyIndicator.showWhile(getShell().getDisplay(), () -> {
```

and then this if-else-block can stay a one-liner:
```suggestion
							_kpair[0] = KeyPair.genKeyPair(getJSch(), __type, keySize);
```

as well as the block below to create the comment.

2024-11-04 00:29 UTC, axmanalad commented
> But with referencing Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1464 I meant to mention it at the end of the commit message body and not only in the headline. The commit headline should still be a descriptive (half) sentence, just like this PR's name/headline. The following body can then contain more details and the mentioned reference.

I see there was a misunderstanding between my thought and your intention. Thank you for the clarification; I changed how the format of the commit message should look like.

> As suggested in [#1464 (comment)](https://github.com/eclipse-platform/eclipse.platform/issues/1464#issuecomment-2439600327), I think the key-size for RSA and DSA should be specified in a static final int constant at the top of this class:
> 
> ```
> private static final String SSH2_PREFERENCE_PAGE_CONTEXT="org.eclipse.jsch.ui.ssh2_preference_page_context"; //$NON-NLS-1$
> private static final int RSA_KEY_SIZE = 4096;
> private static final int DSA_KEY_SIZE = 3072;
> ```
> 
> Then you can create a variable in this method, before `BusyIndicator.showWhile()` that holds the actual keySize used for the specified key type:
> 
> ```
> int keySize = type == KeyPair.RSA ? RSA_KEY_SIZE : DSA_KEY_SIZE;
> final JSchException[] _e=new JSchException[1];
> BusyIndicator.showWhile(getShell().getDisplay(), () -> {
> ```

I really like this implementation of both comments as it looks organized and easier for readability. I readjusted the changes as you have suggested. Thank you for the suggestion.

2024-11-04 18:33 UTC, HannesWell approved these changes
Thank you for the adjustments.

Looks good and works well now. Nice work. :)

2024-11-04 18:34 UTC, merged