Sort content types by priority first
eclipse-platform/eclipse.platform pull request #350
Opened 2023-03-07 21:02 UTC by jonahgraham

This change fixes the problem where the fairly arbitrary depth of the content type carries more weight than the declared priority of that content type.

2023-03-07 21:18 UTC, mickaelistria commented
I think the priority should not matter when 1 contnet-type is a super/sub-type of the other: in such case, the most specialized content-type needs to be returned as it encompass the higher priority one as well.
I would recommend that we write good tests in ContentTypeManagerTest to ensure we first agree on the expectations.

2023-03-08 08:22 UTC, merks commented
@jonahgraham Maybe you have a concrete case/example where the old algorithm produces a result different than the one you would like?

2023-03-08 19:33 UTC, jonahgraham commented
I have created the issue in this repo now, see #351

2023-03-10 16:14 UTC, mickaelistria requested changes
(copied from https://github.com/eclipse-platform/eclipse.platform/issues/351#issuecomment-1461618797 )

> As far as I can tell, depth is not documented as an important factor

Indeed depth is not an important factor per se, the important factor is to return "most specialized" content-type in a lineage, ie basicContentType(priority=high) being a parent of specializedContentType(priority=low), then querying a file which has both content-type should return specializedContentType independently of the priority. That is what enables the most value.
Depth was an implementation choice to achieve that, but it doesn't make sense to use it when the content-types we compare are not of the same lineage: basicContentType has 2 independent children specializedContentType1(priority=high) and specializedContentType2(priority=normal) and that one has a child surSpecializedContentType2(priority=normal), then the expectation is that specializedContentType1 is returned first because depth isn't an interesting criterion to compare specializedContentType1 and surSpecializedContentType2.

An implication of both is this trickier case:
basicContentType
  * specializedContentType1(priority=high)
    * surSpecializedContentType1(priority=low)
  * specializedContentType2(priority=normal)
    * surSpecializedContentType2(priority=normal)
 
Then we would expect that the best content-type here is surSpecializedContentType1. Basically, to fulfill both requirements the priority of a content-type is the max of its lineage.

2023-04-07 22:30 UTC, jonahgraham commented
> [...] should return specializedContentType independently of the priority.

This comment caused me lots of confusion as in practice that isn't what happens unless the content of the file is also analyzed, which seems mostly to only happen when dealing with binary or xml files in practice. I added a new test case, conflict2a and fixed a comment on conflict2 that covers this case. The best summary of the behaviour came when it was last written in [Bug 86915](https://bugs.eclipse.org/bugs/show_bug.cgi?id=86915) back in 2005.

> An implication of both is this trickier case:

My PR does not handle this case. 

Once the CI confirms the tests behave the same as on my machine I will mark this ready for review. I updated the description + summary of the PR to properly reflect the current state.

2023-04-11 08:11 UTC, mickaelistria commented on runtime/bundles/org.eclipse.core.contenttype/src/org/eclipse/core/internal/content/ContentTypeCatalog.java
> +	private static boolean isAncestor(ContentType type1, ContentType type2) {
Why not `type1.isKindOf(type2) || type2.isKindOf(type1)`?

2023-04-12 08:29 UTC, merged

2023-04-12 08:29 UTC, mickaelistria commented
Thank you!