Close project when failing to restore metadata in SaveManager (#377)
eclipse-platform/eclipse.platform pull request #378
Opened 2023-03-27 15:47 UTC by HeikoKlare

As explained in #377, the `SaveManager` does not properly close a project when failing to restore the workspace with inconsistent metadata (e.g. after a process kill). The randomly failing test case `TestBug294854.testDelete` revealed that behavior.

The proposed changes ensure that a project is properly closed in such a case (as intended by the existing code). In addition, the changes fix the indeterministic behavior of `TestBug294854.testDelete` by splitting it up into the cases which randomly occurred before and of which only one was only successful:
1. Kill the process before metadata has been stored in the snapshot job
2. Kill the process after metadata has been stored in the snapshot job

In addition, I propose to replace the `sleep` calls, which try to wait for the snapshot job to be finished, with an according utility that properly waits for it.

2023-03-27 16:06 UTC, HeikoKlare commented
Failing test is already documented (https://github.com/eclipse-platform/eclipse.platform/issues/373).

2023-03-29 10:27 UTC, vogella commented
@jukzi could you also review this one?

2023-03-29 10:35 UTC, jukzi requested changes
little formal detail: Please update the copyright year for SaveManager.

2023-03-29 12:06 UTC, HeikoKlare commented
Thanks for the feedback! I have updated the copyright year and pushed the according change.

2023-03-30 08:15 UTC, iloveeclipse commented
> little formal detail: Please update the copyright year for SaveManager.

I believe copyright years aren't supposed to be updated anymore.

But this was fixed now, so @jukzi can you please approve / disapprove again?

2023-03-30 08:28 UTC, akurtakov commented
It is not required as per https://www.eclipse.org/lists/eclipse-dev/msg10183.html but committers can still do so if they want.

2023-03-30 08:39 UTC, jukzi approved these changes
LGTM

2023-03-30 09:03 UTC, merged

2023-03-30 09:04 UTC, iloveeclipse commented
Thanks everyone.