Optionally require the org.eclipse.jdt.launching.macosx bundle
eclipse-platform/eclipse.platform pull request #390
Opened 2023-03-30 15:17 UTC by laeubi

2023-03-30 15:19 UTC, iloveeclipse requested changes
Please provide commit message **why** this change is needed and which problem it is supposed to solve.

2023-03-30 15:38 UTC, laeubi commented
> > I can only guess and test here ...
> 
> And the later code maintainer will also "guess and test" only to answer a simple question that could be resolved by providing a proper commit comment "why the hack this dependency was added?"

When I know if / how to resolve the issue I can describe why it was done that way, at the moment I first need to evaluate possible options to resolve the issue...

2023-03-31 04:36 UTC, laeubi commented
This now fixes 60 out of 64 of the failing test.
@iloveeclipse please review and then merge.

2023-03-31 05:13 UTC, iloveeclipse approved these changes

2023-03-31 05:14 UTC, merged