WIP, DONT MERGE
eclipse-platform/eclipse.platform pull request #473
Opened 2023-06-01 08:28 UTC by trancexpress

Fixes: #470

2023-09-21 19:48 UTC, akurtakov commented
What is the status of this one?

2023-09-21 19:50 UTC, iloveeclipse commented
> What is the status of this one?

Waits for a review

2023-09-21 20:05 UTC, mickaelistria commented
FWIW, I have trouble to properly understand the use-case. @trancexpress would it be possible to add a test that would demonstrate how to trigger the issue?

2024-04-25 15:21 UTC, iloveeclipse requested changes
Thanks Simeon, this is a very complex code here and very nice to have a working test.

I've wrote my [understanding of the problem](https://github.com/eclipse-platform/eclipse.platform/issues/470#issuecomment-2077079561) and [proposed solution idea](https://github.com/eclipse-platform/eclipse.platform/issues/470#issuecomment-2077539970).

I've pushed rebased, merged & updated PR here to get it easier for the future work - there were massive changes in the resource tests area on master and so the test was not compilable anymore.

Now it compiles & works again.

I believe the code change itself is not enough, I believe we need a different approach which I've tried to draft in https://github.com/eclipse-platform/eclipse.platform/issues/470#issuecomment-2077539970.

2026-04-11 04:31 UTC, closed without merging