Minor simplification of LinkTest
eclipse-platform/eclipse.platform pull request #566
Opened 2023-07-06 22:06 UTC by HannesWell

And investigate why the test is failing.

2023-07-06 22:44 UTC, HannesWell commented
The offending link is probably on `<help-URL>/help/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_help_index.html`
My guess is that the failure of the LinkTest is caused by a space in some Extension-Point documentation in JDT.
Just created https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/278 to hopeful fix it.

The help-sites are
- https://help.eclipse.org/2023-06/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_jdt_launching_vmInstalls.html&cp%3D3_1_1_20
- https://help.eclipse.org/2023-06/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_jdt_launching_vmInstallTypes.html&cp%3D3_1_1_21

2023-07-08 08:14 UTC, HannesWell commented
Even after https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/278 is merged and one I-build has passed the space in beginning is still found.
Stripping the string solves that problem and lets that test pass, but of course it would swallow similar problems in the future.

Does anybody know from which repo the `IWorkbenchHelpSystem` returned by `PlatformUI.getWorkbench().getHelpSystem()` is feed? Do I have to wait for another I-build, for the next milestone or even next release to get the updated version?

2023-07-09 08:06 UTC, Bananeweizen approved these changes
I suggest merging your change and not trying to find the original HTML document. AFAIK blanks around URIs are valid in HTML: https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#valid-url-potentially-surrounded-by-spaces

2023-07-09 08:15 UTC, Bananeweizen commented
If I get it right, the source containing the blank has already been fixed in https://github.com/eclipse-platform/eclipse.platform/issues/561.

2023-07-09 09:08 UTC, merks commented
> If I get it right, the source containing the blank has already been fixed in #561.

Yes that's right.  We did track down the offending files.

2023-07-09 13:28 UTC, Bananeweizen requested changes

2023-07-09 13:28 UTC, Bananeweizen commented on ua/org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/LinkTest.java
> +					URI href = URI.create(matcher.group(1).replace(" ", "%20"));
Sorry @HannesWell. I misread your code during first review. We still need to trim the regex result here to deal with URIs starting/ending with blanks.

```suggestion
					URI href = URI.create(matcher.group(1).strip().replace(" ", "%20"));
```

2023-07-09 13:29 UTC, HannesWell commented
> I suggest merging your change and not trying to find the original HTML document. AFAIK blanks around URIs are valid in HTML: https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#valid-url-potentially-surrounded-by-spaces

Thanks Michael for pointing this out, but unfortunately the help still uses html-4 as mentioned in https://github.com/eclipse-platform/eclipse.platform/issues/561#issuecomment-1627709892. 😞

But I wonder why my changes in the Extension-Point schema are not picked up in an I-build when building the doc?
It looks like the doc is build in the I-builds: 
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/92d943bcd4eeba3187e64fc4f154ab029e234364/eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/buildDoc.xml#L33

Therefore I assumed the change fix is now included, but I still se it in my latest I-build SDK.

2023-07-09 13:35 UTC, Bananeweizen commented
> Thanks Michael for pointing this out, but unfortunately the help still uses html-4 as mentioned in [#561 (comment)](https://github.com/eclipse-platform/eclipse.platform/issues/561#issuecomment-1627709892). 😞

I'm absolutely not an expert on those standards, but looking at the differences between 4 and 5, the href attribute has no relevant changes: https://www.w3.org/TR/html5-diff/#changed-attributes. Therefore URIs starting/ending with blanks should be valid there, too.

2023-07-09 14:20 UTC, Bananeweizen approved these changes
Seems my knowledge of the standard is not sufficient enough, so I'm removing my veto.

2023-07-09 15:23 UTC, HannesWell commented
> > Thanks Michael for pointing this out, but unfortunately the help still uses html-4 as mentioned in [#561 (comment)](https://github.com/eclipse-platform/eclipse.platform/issues/561#issuecomment-1627709892). 😞
> 
> I'm absolutely not an expert on those standards, but looking at the differences between 4 and 5, the href attribute has no relevant changes: https://www.w3.org/TR/html5-diff/#changed-attributes. Therefore URIs starting/ending with blanks should be valid there, too.

Me neither. But in doubt, I would prefer to be stricter in this case, just to be sure.
And with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1209 the fix in the jdt-doc should be picked up in tonights I-build and the failures should be gone.

2023-07-10 06:15 UTC, HannesWell commented
Test is green now.

2023-07-10 06:16 UTC, merged