Run As Context Menu shows Ant Run Configurations multiple times #527
eclipse-platform/eclipse.platform pull request #730
Opened 2023-10-06 08:56 UTC by SudhindraKKulkarni

AntLaunchShortcutWithDialog now implements only ILaunchShortcut interface.
The common implementation of AntLaunchShortcut and AntLaunchShortcutWithDialog are moved to AntLaunchShortcutCommon class

Fixes https://github.com/eclipse-platform/eclipse.platform/issues/527

2023-11-02 11:36 UTC, SarikaSinha requested changes
Even after these changes, I see the duplicate entries.

2023-11-02 12:13 UTC, iloveeclipse commented
@SudhindraKKulkarni : please don't use "merge", we do not allow merge commits. Please rebase your original change on top of master & force push.

2024-08-15 06:13 UTC, jukzi commented
Please update the commit message to describe the fix not the problem. i.e. use "fix ..." or "... a single time"

2025-04-27 10:26 UTC, HeikoKlare commented
Since the mentioned issue https://github.com/eclipse-platform/eclipse.platform/issues/527 has already been resolved, is there any need to still work on this, or can it be closed, @SudhindraKKulkarni?

2025-06-09 08:11 UTC, closed without merging