Add XmlProcessorFactoryTest
eclipse-platform/eclipse.platform pull request #761
Opened 2023-10-24 12:03 UTC by jukzi

And createDocumentBuilderIgnoringDOCTYPE() does not load remote DTDs see https://github.com/eclipse-jdt/eclipse.jdt.debug/issues

2023-10-24 12:09 UTC, jukzi commented
@HannesWell 
test copied from PDE and extended

2023-10-24 17:09 UTC, HannesWell requested changes
I already wondered why the Tests are still in PDE.
Do you want to create a PR to remove them from PDE?

The change itself looks good, but the Test-class  misses the Copyright header (is probably already missing in PDE).

2023-10-25 07:08 UTC, HannesWell approved these changes
Looks good, thanks.

2023-10-27 21:51 UTC, HannesWell commented
Is this ready for submission?

2023-11-02 07:19 UTC, merged